### ISSUE TITLE
ViChatter. Cорокин-Добрилко.

### ISSUE THREAD

**Issue by Sorokin-MS95** [grsu/web-dev#101]
https://github.com/Sorokin-MS95/vichatter

**Comment by Sorokin-MS95** [comment]
Интересно было бы услышать от вас, как правильно работать с oAuth, чтобы не было в дальнейшем проблем с вытягиванием данных из фейсбука и твиттера.

**Comment by irnc** [comment]
> как правильно выносить конфигурацию приложения в переменные окружения?

Посмотрите http://12factor.net/config и пакет https://github.com/indexzero/nconf, а именно его функцию `nconf.env`. Если останутся вопросы - задавайте.
