### ISSUE TITLE
Running Separate Frontend and Backend Servers Within One Project

### ISSUE THREAD

**Issue by LexaGal** [grsu/web-dev#104]
Был вопрос о разделении сервера на хапи на две части - для самого веб сервера и сервера для апи запросов, с которого уже будет обращение в веб серверу (с клиента через апи). Имеется ввиду что-то вроде этого: https://futurestud.io/blog/hapi-how-to-run-separate-frontend-and-backend-servers-within-one-project

**Comment by irnc** [comment]
Да, разделение может быть, а в чём вопрос?

**Comment by LexaGal** [comment]
Надо ли для разделять обязанности серверов так: (1) один контент для клиента выдает(css/js), (2) другой - сами запросы (маршрутизация, доступ к базе данных) обслуживает? Я правильно понял, что 1 при запросе клиента просит у 2 данные из базы данных по известному api, т.е. сам к ней не обращается, 1 сам выдает только статик контент?
