### ISSUE TITLE
Зачёт. 3 курс.

### ISSUE THREAD

**Issue by Stelmashenko-A** [grsu/web-dev#106]
Завтра (11.05.2016) в расписании стоит пара на 13:30 у английской группы, далее две пары - зачёты у обеих групп. По расписанию они все на Лермонтова. На зачёте будут все, поэтому вопрос: действительно ли пары будут у Вас в офисе? (в конференц-зал 20 человек за раз ну ни как не поместяться). Зачёты будут ставиться строго во время второй пары или по мере сдачи успешной сдачи проектов/ответов на вопросы ?

**Comment by irnc** [comment]
По мере сдачи проектов. Начиная с 13:30, английская группа пусть приходит на Лермонтова, всем сразу нет смысла, лучше в некоторой очерёдности - уж сами решите как вам удобней.

Русскоязычная группа пусть приходит к 17:00, в расписаннии этот сдвиг на 20 минут вперёд сегодня отразят.

**Comment by irnc** [comment]
@Stelmashenko-A Андрей, а вы можете забрать ведомости из деканата по дороге на пару?

**Comment by Stelmashenko-A** [comment]
@irnc Нашёл человека, который привезёт ведомость к 13-30

**Comment by irnc** [comment]
Мы уже договорились со старостой. Спасибо!

On Wed, May 11, 2016 at 12:01 PM, Стельмашенко Андрей <
notifications@github.com> wrote:

> @irnc <https://github.com/irnc> Нашёл человека, который привезёт
> ведомость к 13-30
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/grsu/web-dev/issues/106#issuecomment-218402135>
>



-- 
With best regards,
Pavel Zubkou.

Mobile: +375293851118
Skype: pavel.zubkou
