### ISSUE TITLE
Проект: Ближайшая заправка. Ревякин, Неживинская, Плещёва

### ISSUE THREAD

**Issue by vplesheva** [grsu/web-dev#75]
https://github.com/EvgenStudent/CarAssistant

**Comment by irnc** [comment]
[Примерный тематический план](https://docs.google.com/spreadsheets/d/173FNcffcvjuNPE2754K6jipSeke2b3AkuVS35BfqD2c/pubhtml?gid=0&single=true) для заполнения журнала.
