### ISSUE TITLE
Миськевич_Киселёв_4курс_111_112_ПОИТ

### ISSUE THREAD

**Issue by Zenidal** [grsu/web-dev#76]
https://github.com/Zenidal/WeatherForecaster

**Comment by kaban4ik1994** [comment]
New repositories:
1) https://github.com/kaban4ik1994/Weather_Back-End/
2) https://github.com/kaban4ik1994/Weather_Front-End/

**Comment by kaban4ik1994** [comment]
# Modules:
https://github.com/kaban4ik1994/worldweatheronline-node-module
https://github.com/kaban4ik1994/google-geotargeting-node-module

# Already been published.
