### ISSUE TITLE
Проект: CM changelog viewer. Бабай, Кривицкий, Мицкевич.

### ISSUE THREAD

**Issue by MickevichYura** [grsu/web-dev#87]
https://github.com/MickevichYura/rom-changelog
Бабай(@Pixelase), Кривицкий (@UnionOne), Мицкевич(@MickevichYura).

**Comment by irnc** [comment]
Вопрос: где простой сервер и маршрутизация без express?

**Comment by Pixelase** [comment]
@irnc готово, сделан простой без использования express с динамической маршрутизацией (возможные маршруты заполняются при старте программы).
[Ссылка на ветку simple-server](https://github.com/MickevichYura/rom-changelog/tree/simple-server)
