### ISSUE TITLE
Проект: Информация о играх. Деменович, Лавринович

### ISSUE THREAD

**Issue by Demenovich-A-J** [grsu/web-dev#89]
https://github.com/Demenovich-A-J/Game-info

**Comment by irnc** [comment]
Ребята, вы скопировали https://github.com/Stelmashenko-A/Timetable даже не разобрав критические комментарии к первым коммитам того проекта.

Раз уж выбрали вариант копирования, пожалуйста, разберитесь с теми комменатриями.
