### ISSUE TITLE
Проект: Отзывы к фильмам и книгам Буткевич, Дригова, Таранцей

### ISSUE THREAD

**Issue by alena-butkevich** [grsu/web-dev#90]
https://github.com/alena-butkevich/Film-and-books-reviews-

**Comment by irnc** [comment]
Ребята, вы скопировали https://github.com/Stelmashenko-A/Timetable даже не разобрав критические комментарии к первым коммитам того проекта.

Раз уж выбрали вариант копирования, пожалуйста, разберитесь с теми комменатриями.

**Comment by alena-butkevich** [comment]
Вот ссылка на сайт: http://www.nodebeginner.ru.
