### ISSUE TITLE
Family organizer. Новак, Босько, Денищик

### ISSUE THREAD

**Issue by Vanja-Novak** [grsu/web-dev#99]
ПОИТ 121, 1 подгруппа
https://github.com/Vanja-Novak/Famnizer

**Comment by irnc** [comment]
This repository is empty.

Когда планируете начать? Нужна ли помощь с первыми шагами?

On Sunday, 20 March 2016, Vanja-Novak <notifications@github.com> wrote:

> ПОИТ 121, 1 подгруппа
> https://github.com/Vanja-Novak/Famnizer
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grsu/web-dev/issues/99>
>


-- 
With best regards,
Pavel Zubkou.

Mobile: +375293851118
Skype: pavel.zubkou

**Comment by Vanja-Novak** [comment]
Планируем начать разработку в самое ближайшее время.
Для начала планируется создать костяк приложения, подключить БД и сделать минимальный функционал : регистрация, авторизация.
Далее займемся проектированием и по ходу дела будем наполнять приложение различным функционалом.
На первых шагах помощь не понадобиться. Далее если что, будем отписываться.
